"""Add link column to contracts table

Revision ID: 930a8453341a
Revises: 981e3ae4a9af
Create Date: 2025-03-06 17:01:24.838793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930a8453341a'
down_revision = '981e3ae4a9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('link', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'link')
    # ### end Alembic commands ###
