"""新增 MaterialJP 表

Revision ID: d06339d28099
Revises: 930a8453341a
Create Date: 2025-03-10 11:13:28.606928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06339d28099'
down_revision = '930a8453341a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials_jp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_model', sa.String(length=64), nullable=True),
    sa.Column('pid', sa.String(length=64), nullable=True),
    sa.Column('pn', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('keeper', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.Column('sim_info', sa.String(length=64), nullable=True),
    sa.Column('netsuite_dept', sa.String(length=64), nullable=True),
    sa.Column('eis_program', sa.String(length=64), nullable=True),
    sa.Column('eg_account', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('firmware', sa.String(length=64), nullable=True),
    sa.Column('connection_method', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_date', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('pickup_person', sa.String(length=64), nullable=True),
    sa.Column('pickup_order_number', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materials_jp')
    # ### end Alembic commands ###
